config/routes.rb
Rails.application.routes.draw do
  get 'new', to: 'games#new', as: :new
  post 'score', to: 'games#score', as: :score
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'games#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'json'
require 'open-uri'

class GamesController < ApplicationController
  def new
    @letters = []
    8.times do
      @letters << ('a'..'z').to_a.sample
    end
  end

  def score
    @letters = params[:letters]
    word = params[:word]
    word_chars = word.split('')
    url = "https://wagon-dictionary.herokuapp.com/#{word}"
    result_hash = JSON.parse(open(url).read)

    cheat_tester = word_chars.all? do |letter|
      @letters.split('').count(letter) >= word_chars.count(letter)
    end

    if cheat_tester == false
      @result = "You're trying to cheat dickhead!"
    elsif result_hash['found'] == false
      @result = "#{word} does not exist"
    else
      points = result_hash['length'] * result_hash['length']
      @result = "You've earned #{points} with #{word}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>New Game</h1>
<ul class="inline">
  <% @letters.each do |letter| %>
  <li class="list-inline-item">
    <div class="letter">
      <%= letter %>
      <div>
      </li>
      <% end  %>
    </ul>

    <form action="<%= score_path %>" method="post">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= hidden_field_tag :letters, @letters %>
      <div class="form-group">
        <div class="wrapper">
          <label for="wordInput">Word</label>
          <input type="text" name="word" class="form-control" id="wordInput" placeholder="Enter Word">
          <button type="submit" class="btn btn-primary mb-2">submit</button>
        </div>
      </div>
    </form>

app/views/games/score.html.erb
<h1>Games#score</h1>
<p><%= @result %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>